### ISSUE TITLE
`sourceVersion` is incorrect when running action on Pull Request

### ISSUE THREAD

**Issue by pcarney8** [aws-actions/aws-codebuild-run-build#36]
During execution a GitHub Pull Request runs as a detached head, causing the `GITHUB_SHA` version to not match the latest commit. 

This value is then passed to CodeBuild and shows up as the "Resolved Source Version" when the correct value is in `github.event.pull_request.head.sha`

https://github.com/aws-actions/aws-codebuild-run-build/blob/9cc1fe9f1f88b8d7adeb0f7bfaa77473d1d9048f/code-build.js#L117

Trying to override `GITHUB_SHA` in the Run does not work. Could an override be added? Similar to the others?

**Comment by seebees** [comment]
I would like this to just work.
Rather than update this as an option,
I would rather just identify the condition and send this other value.

Some links:
https://github.community/t5/GitHub-Actions/GITHUB-SHA-but-how-to-get-the-latest-commit-reference-on-a/td-p/40873
https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request

As a followup question,
how are you injecting your AWS creds to Pull Requests?

**Comment by andres-lowrie** [comment]
so is there a release cycle cadence or something to subscribe to? in regards to #40 getting merged
